[benchmarks.dedup]
algorithm = "parhash"
input = "${REPO_ROOT}/inputs/expt-500M" 

[benchmarks.isort]
algorithm = "parradix"
input = "${REPO_ROOT}/inputs/expt-500M"

[benchmarks.sort]
algorithm = "sample"
input = "${REPO_ROOT}/inputs/expt-1B"

[benchmarks.hist]
algorithm = "parallel"
input = "${REPO_ROOT}/inputs/expt-500M"
buckets = 500000000

[benchmarks.mis]
algorithm = "rustinc"
input = "${REPO_ROOT}/inputs/Hyperlink2012-Hosts.sym.ag"

[benchmarks.mm]
algorithm = "rustinc"
input = "${REPO_ROOT}/inputs/rmat-50M.ea"

[benchmarks.sf]
algorithm = "incremental"
input = "${REPO_ROOT}/inputs/rmat-20M.ea"

[benchmarks.msf]
algorithm = "incremental"
input = "${REPO_ROOT}/inputs/rmat-20M.wea"

[benchmarks.sa]
algorithm = "par-range"
input = "${REPO_ROOT}/inputs/wikipedia250M.txt"

[benchmarks.bw]
algorithm = "list-rank"
input = "${REPO_ROOT}/inputs/wikipedia250M.txt"

[benchmarks.lrs]
algorithm = "doubling"
input = "${REPO_ROOT}/inputs/wikipedia250M.txt"

[benchmarks.dr]
algorithm = "incremental"
input = "${REPO_ROOT}/inputs/dt_k2M"