[benchmarks.dedup]
algorithm = "parhash"
input = "${REPO_ROOT}/inputs/expt-500M" 

[benchmarks.isort]
algorithm = "parradix"
input = "${REPO_ROOT}/inputs/expt-500M"

[benchmarks.sort]
algorithm = "sample_sort"
input = "${REPO_ROOT}/inputs/expt-1B"

[benchmarks.hist]
algorithm = "parallel"
input = "${REPO_ROOT}/inputs/expt-500M"
buckets = 500000000

[benchmarks.mis]
algorithm = "rustinc"
input = "${REPO_ROOT}/inputs/Hyperlink2012-Hosts.sym.ag"
# input = "${REPO_ROOT}/inputs/USA-road-d-USA.sym.wag"

[benchmarks.mm]
algorithm = "rustinc"
input = "${REPO_ROOT}/inputs/rmat-50M.ea"
# input = "${REPO_ROOT}/inputs/USA-road-d-USA.sym.wag"

[benchmarks.sf]
algorithm = "incremental"
input = "${REPO_ROOT}/inputs/rmat-50M.ea"
# input = "${REPO_ROOT}/inputs/Hyperlink2012-Hosts.sym.ag"
# input = "${REPO_ROOT}/inputs/USA-road-d-USA.sym.wag"

# Doesn't appear to be a 1-to-1 algorithm match between pbbs and rpb
# [benchmarks.msf]
# algorithm = "incremental"
# input = "${REPO_ROOT}/inputs/rmat-20M.wea"
# # input = "${REPO_ROOT}/inputs/USA-road-d-USA.sym.wag"

[benchmarks.sa]
algorithm = "par-range"
input = "${REPO_ROOT}/inputs/wikipedia250M.txt"

[benchmarks.bw]
algorithm = "list-rank"
input = "${REPO_ROOT}/inputs/wikipedia250M.txt"

[benchmarks.lrs]
algorithm = "doubling"
input = "${REPO_ROOT}/inputs/wikipedia250M.txt"

# Doesn't appear to be a 1-to-1 algorithm match between pbbs and rpb
# [benchmarks.bfs]
# input = "${REPO_ROOT}/inputs/Hyperlink2012-Hosts.sym.ag"
# # input = "${REPO_ROOT}/inputs/USA-road-d-USA.sym.wag"
